### ISSUE TITLE
Errors does not have access-control-allow-origin

### ISSUE THREAD

**Issue by ewized** [MC-API/Issues#11]
When some one enters a unknown username the error message does not have the `access-control-allow-origin`. Which makes programs act funky.

An example of a public app that uses the API that acts funky: https://mcuuid.ewized.com

**Comment by njb-said** [comment]
@ewized what mirror does it use so I can isolate the issue?
(Eg: eu.mc-api.net, us.mc-api.net) for requests

**Comment by ewized** [comment]
ATM it uses the `us.mc-api.net` but its going to use `mc-api.net` to pull the subdomain based on your system.

**Comment by njb-said** [comment]
Ok, I am working on a fix for it now

**Comment by ewized** [comment]
@njb-said When the fix gets deployed can you tell me so I can test my web app? Thanks

**Comment by njb-said** [comment]
This should now be resolved, thanks for reporting.
