### ISSUE TITLE
Server Favicon Broken

### ISSUE THREAD

**Issue by Envici** [MC-API/Issues#19]
Whenever I try and connect and find the server favicon, it times out.

**Comment by njb-said** [comment]
@InstanceOfDev Could you tell me the ip you are trying?

**Comment by InstanceOfDev** [comment]
It seems to be every server I have tried. These ones so far:

- mc.hypixel.net
- play.galaxycube.net
- play.hivemc.com

**Comment by njb-said** [comment]
I think most server info and favicon issues have been fixed since I rewrote the server. SRV records are still an issue though
