### ISSUE TITLE
Uuid to username problem

### ISSUE THREAD

**Issue by pvpteams** [MC-API/Issues#21]
Hi! I have php website that connects to mysql database and get from there players uuid and his deaths etc.
So i use your uuid to username api. It have worked very good but now it doesnt work.
At the website its saying this:
Warning: file_get_contents(https://eu.mc-api.net/v3/name/34b53065-1281-4193-a39c-c0b7339ac8ac): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /var/www/html/top-party.php on line 79

I tried another api and it worked, but its very slow. I would want to use your eu api :)

**Comment by ImNatho** [comment]
Hey,

Give it another go; The website may have been down during that time. If it still doesn't work could you please paste line 79 of top-party.php?

-N

**Comment by pvpteams** [comment]
Its working now. Thanks!
