### ISSUE TITLE
Doesnt work anymore.

### ISSUE THREAD

**Issue by Rizzkin** [MC-API/Issues#22]
Hello,

https://eu.mc-api.net/v3/uuid/ doesn't work anymore. It can check the UUID of available names but it doesn't check the UUID of like this.

The name BAT comes available soon. so I wanna grab the UUID so I can make a function which calculates when it gets available.

I tried yesterday and it worked, tried 3 hours later and it didnt.
Help me with this please, how can I get the UUID of a name like bat when its unavailable for couple days? So no one has the name, but its stil locked.

Regards

**Comment by njb-said** [comment]
Hi,
Could you explain to me the issue you are having?
I have just checked and the username "Bat" is available. (You can check [here](https://iaero.me/mcchecker) to see if the username is available or not)
You cannot get the UUID of the username until someone has it as their name (because it doesn't exist)

Hope this helps :smiley:

**Comment by Rizzkin** [comment]
Thanks for your fast response,

Really appreciate it!

Do you know how to calculate it then, calculate the time until the name is available. 

Because I am developing a sniper and about this issue I am clueless. Do you know how to calculate until a new name is available? 

Is there an API for it?

Do you have skype, mine is ifsquiiz!

Verstuurd vanaf mijn iPhone

**Comment by njb-said** [comment]
You could use this [this](https://mc-api.net/example/history) to find out when they last changed their uuid and work off it.
Don't really know specifics as I haven't looked into it before.

**Comment by Rizzkin** [comment]
Would you wanna be my partner to make a MC sniper with my associate Jefferson Prince the CEO of www.StarnetEclipse.com

One of the employees who work airh his ingame stuff wil write the code.


Verstuurd vanaf mijn iPhone
