### ISSUE TITLE
Multiple UUIDs at a time ?

### ISSUE THREAD

**Issue by PunKeel** [MC-API/Issues#24]
Hello,

In order not to flood your API, I think it might be cool if we could query multiple UUID at a single time, the  same way names->uuid works.

The old API wouldn't have to change, but `https://eu.mc-api.net/v3/name/b05881186e75410db2db4d3066b223f7,61699b2ed3274a019f1e0ea8c3f06bc6` would return `[{...}, {...}]`. This way, it's backward compatible.

Do you think this is possible? (There is no UUIDs->Names API with Mojang ...)

Regards!

**Comment by ImNatho** [comment]
Yes, that would be very handy. But I think Mojang still have a limit on the amount of UUIDs you can query every 30 seconds? @njb-said can/cannot confirm?

**Comment by njb-said** [comment]
Yeah, that's correct @ImNatho they have ridiculous rate limiting.
Potentially I could add multiple uuids but it would probably fail because of the rate limiting. :unamused:

**Comment by ImNatho** [comment]
Add me to the server repo @njb-said . I have an idea to implement this.

**Comment by ImNatho** [comment]
Impossible with the rate limits and issues we currently have. A Query for 5 uuids would take at least 5 seconds to complete vs 1 uuid < 1 second.
