### ISSUE TITLE
Yeah its down. Bad gateway

### ISSUE THREAD

**Issue by Envici** [MC-API/Issues#30]
This is quite annoying. This is holding up my entire network. The entire API (both regions) are down.

**Comment by njb-said** [comment]
Hi, apologises for this, I am working on a fix.
After it is fixed I am going to put something in place to hopefully prevent this happening again.

**Comment by njb-said** [comment]
Fixed both regions. Will do something to stop this in the future later today.
Apologises again for the inconvenience.
