### ISSUE TITLE
The API does not understand SRV records

### ISSUE THREAD

**Issue by IvanTrendafilov** [MC-API/Issues#32]
For instance, one can connect to emerald.voxmc.com from the MC client, but the API fails:

https://eu.mc-api.net/v3/server/info/emerald.voxmc.com/csv

When using a standard A record and the port, it works

https://us.mc-api.net/v3/server/info/emerald2.voxmc.com:25567/csv

**Comment by njb-said** [comment]
We are aware of this issue and unfortunately we don't have a way to resolve SRV records as of now that doesn't increase API response times. It is something we're looking into but it isn't a top priority right now, I suggest (for now at least) just using an A record with our API.

**Comment by njb-said** [comment]
Sorry for the late response, this has been fixed with the latest update, which has is also a redesign of the documentation. 😃
