### ISSUE TITLE
The cache system in UUID to Name store the query instead of the actual name

### ISSUE THREAD

**Issue by KareemMAX** [MC-API/Issues#34]
When I tried to use the api the first time looked like this
```json
{"full_uuid":"c054d78e-e15a-4633-be16-6650c0855efb","source":"mojang","query":"kareemmax","name":"KareemMAX","took":254,"uuid":"c054d78ee15a4633be166650c0855efb"}
```
the second time looked like this
```json
{"full_uuid":"c054d78e-e15a-4633-be16-6650c0855efb","source":"cache","query":"kareemmax","name":"kareemmax","took":1,"uuid":"c054d78ee15a4633be166650c0855efb"}
```
Please solve this as soon as you can @ImNatho

**Comment by ImNatho** [comment]
Wait. What part is the issue? One was loaded from our cache and the other was retrieved from mojang's servers? Or is the the "name" value?

**Comment by KareemMAX** [comment]
Your server seems to be save the query in the cache in the "name" value so when I try to get it from the cache the "name" value is the previous query
I tried to use different name and different times and in lowercase or uppercase and the problem still the same

**Comment by ImNatho** [comment]
Okay, that's a quick fix. I'll add it in before the skins section

**Comment by KareemMAX** [comment]
The mojang one was correct, the problem with the cache system

**Comment by KareemMAX** [comment]
Ok I'm waiting

**Comment by ImNatho** [comment]
@KareemMAX I have UNI today so It might take a few hours before this is merged into master.

**Comment by KareemMAX** [comment]
No problem I will change my code when you done

**Comment by ImNatho** [comment]
Pushed to master. Waiting for tests and deploy.

**Comment by ImNatho** [comment]
Deployed
