### ISSUE TITLE
UUID down

### ISSUE THREAD

**Issue by jake44264** [MC-API/Issues#36]
the eu uuid server is currently down.

**Comment by njb-said** [comment]
@jake44264 It's up for me! Could you show me a screenshot or an error you might be getting?
![http://i.imgur.com/UiM9c2o.png](http://i.imgur.com/UiM9c2o.png)

**Comment by jake44264** [comment]
if i do https://eu.mc-api.net/v3/uuid/Jake4 it doesn't work.

**Comment by jake44264** [comment]
it says Unknown Username on all the accounts.

**Comment by njb-said** [comment]
Ok, I have checked the logs and it seems Mojang's API rate limit is causing issues. I suggest you try us.mc-api.net for now.

I am actively looking into getting more servers to try to work around the rate limits

**Comment by njb-said** [comment]
@jake44264 I think the issue has fixed itself, as I mentioned I am investigating getting more servers however it is quite expensive to do so bear with me! :+1: 
Sorry for the inconvenience this issue may have caused.
