### ISSUE TITLE
Mojang rate-limit causing errors with UUID and Username resolution.

### ISSUE THREAD

**Issue by ImNatho** [MC-API/Issues#40]
Mojang's API rate-limit has been causing issues with our API due to some spiked usage.
The current limit is about 600 requests every 10 minutes (Calculated per second which is 1 request/s)

Current solution: Add more nodes to the cloud.
Downside: Although it is too expensive without any form of income.

Working on a address proxy system to help bypass the set limits (This will probably be just as costly since Mojang don't support IPv6 as of yet.).
An alternative solution is to introduce a Freemium payment system with a limited free tier and a pay-per-request-per-second system.

I have thought about using Google Cloud Services or Amazon Cloud Services as another option since the requests would/could be sent from different addresses from the cloud. Although this would purely be random and there would be no way to manage when the address changes.

**Comment by xXAndrew28Xx** [comment]
Thanks for this. I was debugging like crazy trying to figure out why my server threw out 2GB in stacktraces. I tracked it down this API.

**Comment by njb-said** [comment]
Unfortunately we have deprecated our UUID, Name and History APIs, therefore I'm going to close this issue. :unamused: 
For more information about this please visit [mc-api.net/update-v4](https://mc-api.net/update-v4).

If you need any more help please let me know on here or [on our discord](https://discord.gg/5SX6Uk3).
