### ISSUE TITLE
EU API throws "Unknown Username" Error

### ISSUE THREAD

**Issue by pavog** [MC-API/Issues#42]
Sometimes I get the `{"error":"Unknown Username","query":"<name>"}` error when I try parsing a username of me or my friends using the eu api `https://eu.mc-api.net/v3/uuid/<name>`.
When I use the us api `https://us.mc-api.net/v3/uuid/<name>` it always works.

To replicate the error try my Minecraftname: EvilCodes

**EU API**
`https://eu.mc-api.net/v3/uuid/EvilCodes`
`{"error":"Unknown Username","query":"EvilCodes"}`

**US API**
`https://us.mc-api.net/v3/uuid/EvilCodes`
`{"full_uuid":"ac4a2732-dd44-408b-8d4e-e0b6de14b2c1","source":"cache","query":"EvilCodes","name":"EvilCodes","took":1,"uuid":"ac4a2732dd44408b8d4ee0b6de14b2c1"}`

I also tested some other names (of my friends) and it did not work on EU API (just US).
When I test Mojangsters names it works (on US and EU)...

**Comment by ImNatho** [comment]
That issue is being addressed. It is caused by mojang's api rate limit, not
our api. We are currently doing a rewrite of our server to help prevent
this.

On Tue, 7 Jun 2016, 3:16 AM Paul Vogel <notifications@github.com> wrote:

> I always get the {"error":"Unknown Username","query":"<name>"} error when
> I try parsing a username of me or my friends using the eu api
> https://eu.mc-api.net/v3/uuid/<name>.
> When I use the us api https://us.mc-api.net/v3/uuid/<name> it always
> works.
>
> To replicate the error try my Minecraftname: EvilCodes
>
> *EU API*
> https://eu.mc-api.net/v3/uuid/EvilCodes
> {"error":"Unknown Username","query":"EvilCodes"}
>
> *US API*
> https://us.mc-api.net/v3/uuid/EvilCodes
>
> {"full_uuid":"ac4a2732-dd44-408b-8d4e-e0b6de14b2c1","source":"cache","query":"EvilCodes","name":"EvilCodes","took":1,"uuid":"ac4a2732dd44408b8d4ee0b6de14b2c1"}
>
> I also tested some other names (of my friends) and it did not work on EU
> API (just US).
> When I test Mojangsters names it works (on US and EU)...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MC-API/Issues/issues/42>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACliOA-Pa3N3qdjaS1VSHpUBiUPyp7Grks5qJF0PgaJpZM4IvJIh>
> .
>
-- 
- N

**Comment by ImNatho** [comment]
It also doesn't help that the "Not Found" result is cached for 30 minutes.
