### ISSUE TITLE
Forbidden 403 for Vietnam

### ISSUE THREAD

**Issue by games647** [MC-API/Issues#44]
First of all I'd like to thank you for the great service. I donated some dollars. I hope the paypal-address is correct. Could you maybe post the email again?

So now the issue. One of my users is getting a 403 when accessing the API from Vietnam. No one else had this issue earlier. I found the other related 403 issue tickets, but it seemed to be solved or it appears again. 

I do set a useragent, but it's not a browser useragent. Maybe you could adjust the security settings in Couldflare, because I know that person have to solve the captcha too while using a browser.

**Comment by ImNatho** [comment]
Afaik @njb-said had to region block some areas... But I'll let him answer this.

**Comment by njb-said** [comment]
Interesting, I don't think vietnam is blocked.
I have edited a few settings, which may help the problem.
