### ISSUE TITLE
Username -> UUID always returns "Unknown-Username"

### ISSUE THREAD

**Issue by flammablesports** [MC-API/Issues#45]
https://eu.mc-api.net/v3/uuid/thecampingrusher/csv returns "Unknown-Username" however, UUID -> Username returns the uuid correctly. Both US and EU servers are affected by this.

**Comment by njb-said** [comment]
This is likely to do with the current issues we are having with Mojangs rate limits.
We are working on an api-key system to avoid certain users hogging the API unfairly.

**Comment by njb-said** [comment]
Unfortunately we have deprecated our UUID, Name and History APIs, therefore I'm going to close this issue. :unamused: 
For more information about this please visit [mc-api.net/update-v4](https://mc-api.net/update-v4).

If you need any more help please let me know on here or [on our discord](https://discord.gg/5SX6Uk3).
