### ISSUE TITLE
Username -> UUID 'Unknown username'

### ISSUE THREAD

**Issue by zTryhqrd** [MC-API/Issues#46]
Hello,
When I try to use the api for my username, it says 'Unknown Username', why? It's not only for me, only for other players..

https://eu.mc-api.net/v3/uuid/tewtryhard

Thanks.

**Comment by njb-said** [comment]
Sorry about this, please see #45

**Comment by njb-said** [comment]
Unfortunately we have deprecated our UUID, Name and History APIs, therefore I'm going to close this issue. :unamused: 
For more information about this please visit [mc-api.net/update-v4](https://mc-api.net/update-v4).

If you need any more help please let me know on here or [on our discord](https://discord.gg/5SX6Uk3).
