### ISSUE TITLE
Caching of UUID-Requests doesn't affect the Migrated API

### ISSUE THREAD

**Issue by games647** [MC-API/Issues#47]
I found the migrated API endpoint and wanted to use it, because it caches the entries much longer. 

Although your server seems to be rate-limited again, I could request the notch UUID with the following route: (proparly because it's a popular example and is cached)
https://us.mc-api.net/v3/uuid/notch

But when I try to acces the migrated route: 
https://us.mc-api.net/v3/migrated/Notch

It says unknown username. 

My suggestion is to cache both when requests are made on the UUID-route, because according to the [API-Wiki](http://wiki.vg/Mojang_API#Username_-.3E_UUID_at_time) a legacy property will be present if it's a not migrated account.

**Comment by njb-said** [comment]
I will look into this with our upcoming update, the reason it doesn't happen now is because we solely cache the username and migrated value key-pair without the UUID at all.

Thanks for the suggestion! 👍

**Comment by njb-said** [comment]
Unfortunately we have deprecated our UUID, Name and History APIs, therefore I'm going to close this issue. :unamused: 
For more information about this please visit [mc-api.net/update-v4](https://mc-api.net/update-v4).

If you need any more help please let me know on here or [on our discord](https://discord.gg/5SX6Uk3).
