### ISSUE TITLE
API favicons - ability to choose size

### ISSUE THREAD

**Issue by WulfGamesYT** [MC-API/Issues#57]
With the https://mc-api.net/ api for favicons, can you add the ability to get a custom sized favicon (in pixels), so instead of just 64px by 64px, you can get 20px by 20px using something like:

https://mc-api.net/v3/server/favicon/mc.hypixel.net?size=20

Thanks!

**Comment by badnatho** [comment]
The image provided by the server ping response packet is 64x64 pixels. The client can manipulate that image however they see fit. Implementing this feature would not be a priority as it would just add unnecessary load to our servers when there are plentiful libraries out there that scale images. Not to mention html/css image scaling for web pages.
