### ISSUE TITLE
Unknown Class (Java UUID API)

### ISSUE THREAD

**Issue by Zeryther** [MC-API/Issues#6]
It can't find the class com.jcabi.aspects.Async in net.mcapi.uuid.queries.UUIDQuery and net.mcapi.uuid.queries.NameQuery

**Comment by njb-said** [comment]
Are you using Maven?

**Comment by Zeryther** [comment]
Will check it out. I often had these problems. People suggested me to use Maven, but I didn't :/

**Comment by njb-said** [comment]
I have now removed jcabi but replaced it with unirest (which is a really cool http library for java and other languages)
